In [1]:
import pandas as pd
import os

dataset_folder = r"C:\Users\michael\Desktop\IDX Exchange\Files\datasets"
os.chdir(dataset_folder)

In [2]:
df_sold = pd.read_csv("CRMLSSold_3.csv", low_memory = False)
df_listings = pd.read_csv("CRMLSListing_3.csv", low_memory = False)

In [3]:
df_sold.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,OriginatingSystemName,OriginatingSystemSubName,year_month,rate_30yr_fixed
0,ContraCosta,ContraCosta,"Tile,Wood",NaN,False,5000000.0,1095075487,2024-01-18,5000000.0,Erin,...,False,3.0,NaN,94595,NaN,30240.0,CRMLS,CRMLS_CCBE,2024-01,6.6425
1,NaN,Mlslistings,NaN,False,NaN,NaN,1079166779,2024-01-30,858000.0,David,...,False,2.0,Palm Springs Unified,92262,NaN,13504.0,CRMLS,CRMLS_MLSL,2024-01,6.6425
2,Glendale,Southland,NaN,False,False,1890500.0,1075037759,2024-01-29,1890500.0,Karen,...,False,2.0,Los Angeles Unified,91356,0.0,17873.0,CRMLS,CRMLS_CRM,2024-01,6.6425
3,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,2024-01-02,2100000.0,Jennifer,...,False,3.0,San Luis Coastal Unified,93401,0.0,11219.0,CRMLS,CRMLS_CRM,2024-01,6.6425
4,CoastalMendocino,CoastalMendocino,Tile,True,False,1950000.0,1063453216,2024-01-22,1950000.0,Kira,...,NaN,2.0,NaN,95437,NaN,74487.6,CRMLS,CRMLS_CRF,2024-01,6.6425

In [4]:
df_listings.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1,year_month,rate_30yr_fixed
0,759000.0,1159972295,NaN,NaN,Richard,Sirois,33.738910,-116.198447,42680 Incantata Place,Residential,...,False,2.0,Desert Sands Unified,92203,NaN,289.0,5227.0,42680 Incantata Place,2024-01,6.6425
1,320000.0,1159871345,2026-05-11,320000.0,Nicholas,Miller,33.842793,-116.481803,28388 Desert Princess Drive,Residential,...,False,1.0,NaN,92234,Coldwell Banker Realty,855.0,1307.0,28388 Desert Princess Drive,2024-01,6.6425
2,115900.0,1153320466,2026-04-10,160000.0,Heidi,Dunk-Vincent,39.125903,-122.861472,6900 Glenn,Residential,...,False,1.0,Upper Lake Union,95464,Noble Realty,0.0,3920.0,6900 Glenn,2024-01,6.6425
3,2500000.0,1146529264,2026-04-17,2000000.0,Clifford,Stevens,34.150964,-118.390267,4415 Morella Ave,Residential,...,False,2.0,Los Angeles Unified,91607,Equity Union,0.0,9906.0,4415 Morella Ave,2024-01,6.6425
4,3200000.0,1118382573,2025-05-21,3200000.0,Trudy,McGrath,33.028788,-117.264434,1200 Cardiff Drive,Residential,...,False,0.0,San Dieguito Union,92024,NonMember/Member-Other Board,0.0,54885.6,1200 Cardiff Drive,2024-01,6.6425

In [5]:
print("Row Counts (BEFORE):")
print(f"- Sold: {len(df_sold)}")
print(f"- Listings: {len(df_listings)}")

Row Counts (BEFORE):
- Sold: 455658
- Listings: 504466

In [6]:
sold_dtypes = sorted(df_sold.dtypes.unique().astype(str).tolist())
listings_dtypes = sorted(df_listings.dtypes.unique().astype(str).tolist())

print("Data Type Confirmations (BEFORE):")
print(f"- Sold: {sold_dtypes}")
print(f"- Listings: {listings_dtypes}")

Data Type Confirmations (BEFORE):
- Sold: ['float64', 'int64', 'object']
- Listings: ['float64', 'int64', 'object']

In [7]:
# Fields transformed from strings to datetime format, allowing for reliable datetime-based analysis.
date_fields = ["CloseDate", "PurchaseContractDate", "ListingContractDate", "ContractStatusChangeDate"]

for field in date_fields:
    df_sold[field] = pd.to_datetime(df_sold[field])
    df_listings[field] = pd.to_datetime(df_listings[field])

In [285]:
# WIP

# Remove unnecessary or redundant columns
# {Document every transformation you made & why.}

In [286]:
# WIP

# Handle missing values appropritately
# {Document every transformation you made & why.}

In [287]:
# WIP

# Ensure numeric fields are properly typed
# {Document every transformation you made & why.}

In [19]:
df_sold_flagged = df_sold.copy()
df_listings_flagged = df_listings.copy()

In [20]:
def flag_invalid_numeric_values(df_flagged):
    # ClosePrice <= 0
    df_flagged["non_positive_close_price_flag"] = 0
    df_flagged.loc[(df_flagged.ClosePrice <= 0), "non_positive_close_price_flag"] = 1

    # LivingArea <= 0
    df_flagged["non_positive_living_area_flag"] = 0
    df_flagged.loc[(df_flagged.LivingArea <= 0), "non_positive_living_area_flag"] = 1

    # DaysOnMarket < 0
    df_flagged["negative_days_on_market_flag"] = 0
    df_flagged.loc[(df_flagged.DaysOnMarket < 0), "negative_days_on_market_flag"] = 1

    # Negative Bedrooms or Bathrooms
    df_flagged["negative_bedrooms_flag"] = 0
    df_flagged.loc[(df_flagged.BedroomsTotal < 0), "negative_bedrooms_flag"] = 1

    df_flagged["negative_bathrooms_flag"] = 0
    df_flagged.loc[(df_flagged.BathroomsTotalInteger < 0), "negative_bathrooms_flag"] = 1

In [21]:
def flag_date_consistency(df_flagged):
    # ListingContractDate AFTER PurchaseContractDate
    df_flagged["listing_after_close_flag"] = 0
    df_flagged.loc[(df_flagged.ListingContractDate > df_flagged.CloseDate), "listing_after_close_flag"] = 1

    # PurchaseContractDate AFTER CloseDate
    df_flagged["purchase_after_close_flag"] = 0
    df_flagged.loc[(df_flagged.PurchaseContractDate > df_flagged.CloseDate), "purchase_after_close_flag"] = 1

    # ListingContractDate AFTER PurchaseContractDate AFTER CloseDate
    df_flagged["negative_timeline_flag"] = 0
    df_flagged.loc[(df_flagged.ListingContractDate > df_flagged.PurchaseContractDate) & (df_flagged.PurchaseContractDate > df_flagged.CloseDate), "negative_timeline_flag"] = 1

In [22]:
def flag_geographic_data(df_flagged):
    # Missing coordinates (Latitude or Longitude is null)
    df_flagged["null_coords_flag"] = 0
    df_flagged.loc[(df_flagged.Latitude.isna() == True) | (df_flagged.Longitude.isna() == True), "null_coords_flag"] = 1

    # Latitude = 0 or Longitude = 0 (sentinel null values)
    df_flagged["sentinel_null_coords_flag"] = 0
    df_flagged.loc[(df_flagged.Latitude == 0) | (df_flagged.Longitude == 0), "sentinel_null_coords_flag"] = 1

    # Longitude > 0 errors (California coordinates should be negative)
    df_flagged["positive_longitude_flag"] = 0
    df_flagged.loc[(df_flagged.Longitude > 0), "positive_longitude_flag"] = 1

    # Out-of-state or implausible coordinates
    df_flagged["out_of_state_coords_flag"] = 0
    df_flagged.loc[(df_flagged.Latitude > 42) | (df_flagged.Latitude < 32.53) | (df_flagged.Longitude > -114.13) | (df_flagged.Longitude < -124.41), "out_of_state_coords_flag"] = 1

In [23]:
flag_invalid_numeric_values(df_sold_flagged)
flag_invalid_numeric_values(df_listings_flagged)

flag_date_consistency(df_sold_flagged)
flag_date_consistency(df_listings_flagged)

flag_geographic_data(df_sold_flagged)
flag_geographic_data(df_listings_flagged)

In [24]:
df_sold_flagged.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,...,negative_days_on_market_flag,negative_bedrooms_flag,negative_bathrooms_flag,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag,null_coords_flag,sentinel_null_coords_flag,positive_longitude_flag,out_of_state_coords_flag
0,ContraCosta,ContraCosta,"Tile,Wood",NaN,False,5000000.0,1095075487,2024-01-18,5000000.0,Erin,...,0,0,0,0,0,0,0,0,0,0
1,NaN,Mlslistings,NaN,False,NaN,NaN,1079166779,2024-01-30,858000.0,David,...,0,0,0,0,0,0,0,0,0,0
2,Glendale,Southland,NaN,False,False,1890500.0,1075037759,2024-01-29,1890500.0,Karen,...,0,0,0,0,0,0,0,0,0,0
3,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,2024-01-02,2100000.0,Jennifer,...,0,0,0,0,0,0,0,0,0,0
4,CoastalMendocino,CoastalMendocino,Tile,True,False,1950000.0,1063453216,2024-01-22,1950000.0,Kira,...,1,0,0,0,0,0,0,0,0,0

In [25]:
df_listings_flagged.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,negative_days_on_market_flag,negative_bedrooms_flag,negative_bathrooms_flag,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag,null_coords_flag,sentinel_null_coords_flag,positive_longitude_flag,out_of_state_coords_flag
0,759000.0,1159972295,NaT,NaN,Richard,Sirois,33.738910,-116.198447,42680 Incantata Place,Residential,...,0,0,0,0,0,0,0,0,0,0
1,320000.0,1159871345,2026-05-11,320000.0,Nicholas,Miller,33.842793,-116.481803,28388 Desert Princess Drive,Residential,...,0,0,0,0,0,0,0,0,0,0
2,115900.0,1153320466,2026-04-10,160000.0,Heidi,Dunk-Vincent,39.125903,-122.861472,6900 Glenn,Residential,...,0,0,0,0,0,0,0,0,0,0
3,2500000.0,1146529264,2026-04-17,2000000.0,Clifford,Stevens,34.150964,-118.390267,4415 Morella Ave,Residential,...,0,0,0,0,0,0,0,0,0,0
4,3200000.0,1118382573,2025-05-21,3200000.0,Trudy,McGrath,33.028788,-117.264434,1200 Cardiff Drive,Residential,...,0,0,0,0,0,0,0,0,0,0

In [26]:
print("Invalid Numeric Values")

print("- Sold:")
print(f"  - (ClosePrice <= 0): {len(df_sold_flagged[df_sold_flagged.non_positive_close_price_flag == 1])}")
print(f"  - (LivingArea <= 0): {len(df_sold_flagged[df_sold_flagged.non_positive_living_area_flag == 1])}")
print(f"  - (DaysOnMarket < 0): {len(df_sold_flagged[df_sold_flagged.negative_days_on_market_flag == 1])}")
print(f"  - (Negative Bedrooms): {len(df_sold_flagged[df_sold_flagged.negative_bedrooms_flag == 1])}")
print(f"  - (Negative Bathrooms): {len(df_sold_flagged[df_sold_flagged.negative_bathrooms_flag == 1])}")

print("- Listings:")
print(f"  - (ClosePrice <= 0): {len(df_listings_flagged[df_listings_flagged.non_positive_close_price_flag == 1])}")
print(f"  - (LivingArea <= 0): {len(df_listings_flagged[df_listings_flagged.non_positive_living_area_flag == 1])}")
print(f"  - (DaysOnMarket < 0): {len(df_listings_flagged[df_listings_flagged.negative_days_on_market_flag == 1])}")
print(f"  - (Negative Bedrooms): {len(df_listings_flagged[df_listings_flagged.negative_bedrooms_flag == 1])}")
print(f"  - (Negative Bathrooms): {len(df_listings_flagged[df_listings_flagged.negative_bathrooms_flag == 1])}")

Invalid Numeric Values
- Sold:
  - (ClosePrice <= 0): 0
  - (LivingArea <= 0): 161
  - (DaysOnMarket < 0): 48
  - (Negative Bedrooms): 0
  - (Negative Bathrooms): 0
- Listings:
  - (ClosePrice <= 0): 0
  - (LivingArea <= 0): 261
  - (DaysOnMarket < 0): 43
  - (Negative Bedrooms): 0
  - (Negative Bathrooms): 0

In [27]:
print("Date Consistency Checks")

print("- Sold:")
print(f"  - (Listing AFTER Close): {len(df_sold_flagged[df_sold_flagged.listing_after_close_flag == 1])}")
print(f"  - (Purchase AFTER Close): {len(df_sold_flagged[df_sold_flagged.purchase_after_close_flag == 1])}")
print(f"  - (Negative Timeline): {len(df_sold_flagged[df_sold_flagged.negative_timeline_flag == 1])}")

print("- Listings:")
print(f"  - (Listing AFTER Close): {len(df_listings_flagged[df_listings_flagged.listing_after_close_flag == 1])}")
print(f"  - (Purchase AFTER Close): {len(df_listings_flagged[df_listings_flagged.purchase_after_close_flag == 1])}")
print(f"  - (Negative Timeline): {len(df_listings_flagged[df_listings_flagged.negative_timeline_flag == 1])}")

Date Consistency Checks
- Sold:
  - (Listing AFTER Close): 81
  - (Purchase AFTER Close): 92
  - (Negative Timeline): 1
- Listings:
  - (Listing AFTER Close): 82
  - (Purchase AFTER Close): 94
  - (Negative Timeline): 1

In [28]:
print("Geographic Data Checks")

print("- Sold:")
print(f"  - (Missing Coords): {len(df_sold_flagged[df_sold_flagged.null_coords_flag == 1])}")
print(f"  - (Latitude/Longitude = 0): {len(df_sold_flagged[df_sold_flagged.sentinel_null_coords_flag == 1])}")
print(f"  - (Longitude > 0): {len(df_sold_flagged[df_sold_flagged.positive_longitude_flag == 1])}")
print(f"  - (Out-of-State Coords): {len(df_sold_flagged[df_sold_flagged.out_of_state_coords_flag == 1])}")

print("- Listings:")
print(f"  - (Missing Coords): {len(df_listings_flagged[df_listings_flagged.null_coords_flag == 1])}")
print(f"  - (Latitude/Longitude = 0): {len(df_listings_flagged[df_listings_flagged.sentinel_null_coords_flag == 1])}")
print(f"  - (Longitude > 0): {len(df_listings_flagged[df_listings_flagged.positive_longitude_flag == 1])}")
print(f"  - (Out-of-State Coords): {len(df_listings_flagged[df_listings_flagged.out_of_state_coords_flag == 1])}")

Geographic Data Checks
- Sold:
  - (Missing Coords): 53637
  - (Latitude/Longitude = 0): 44
  - (Longitude > 0): 34
  - (Out-of-State Coords): 110
- Listings:
  - (Missing Coords): 49467
  - (Latitude/Longitude = 0): 62
  - (Longitude > 0): 69
  - (Out-of-State Coords): 218

In [29]:
# WIP

print("Row Counts (AFTER):")
print(f"- Sold: {len(df_sold)}")
print(f"- Listings: {len(df_listings)}")

Row Counts (AFTER):
- Sold: 455658
- Listings: 504466

In [30]:
# WIP

sold_dtypes = sorted(df_sold.dtypes.unique().astype(str).tolist())
listings_dtypes = sorted(df_listings.dtypes.unique().astype(str).tolist())

print("Data Type Confirmations (AFTER):")
print(f"- Sold: {sold_dtypes}")
print(f"- Listings: {listings_dtypes}")

Data Type Confirmations (AFTER):
- Sold: ['datetime64[ns]', 'float64', 'int64', 'object']
- Listings: ['datetime64[ns]', 'float64', 'int64', 'object']

In [284]:
# WIP

# Save datasets as CSVs
# DATASET.to_csv("CRMLSSold_4.csv", index = False)
# DATASET.to_csv("CRMLSListing_4.csv", index = False)